version: '3.7'

x-template: &template
  networks:
    - danis-network
  env_file:
    - .env
  volumes:
    - .:/opt/app:cached
  tmpfs:
    - /tmp
    - /tmp/php-opcache
  depends_on:
    - db
  build:
    context: .
    dockerfile: build/local/Dockerfile
  image: php-base:7.4.5-fpm

services:
  web:
    <<: *template
    environment:
      - APP_NAME=web
    expose:
      - 9000

  db:
    image: postgres:12.2
    networks:
      - danis-network
    volumes:
      - ./var/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    container_name: danis_db
    ports:
      - 6432:5432

  webserver:
    networks:
      - danis-network
    image: nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - './build/local/nginx.conf:/etc/nginx/conf.d/default.conf'
    restart: always

networks:
  danis-network:
    driver: "bridge"
    driver_opts:
      com.docker.network.driver.mtu: 1400
